FROM cuda:12.2.0-runtime-ubuntu20.04-python3.10
RUN apt update

WORKDIR /app

COPY . .
RUN pip3 install --upgrade pip3
RUN pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121

RUN pip3 install -e 
EXPOSE 6581

CMD ["serve.sh"]

